scalar Date

enum SortFilmsBy {
  releaseDate
  episodeId
}

enum SortByNameOrId {
  id
  name
}

enum Gender {
  male
  female
}

type Film {
  created: Date
  director: String!
  edited: Date
  episodeId: Int!
  id: Int!
  openingCrawl: String!
  producer: String!
  releaseDate: String!
  title: String!
}

type Person {
  # homeworld: 1
  birthYear: String
  created: Date
  edited: Date
  eyeColor: String
  gender: Gender
  hairColor: [String]
  height: Float
  id: Int!
  mass: Float
  name: String!
  skinColor: [String]
}

type Planet {
  edited: Date
  created: Date
  climate: [String]
  id: Int!
  surfaceWater: Float
  name: String!
  diameter: Int
  rotationPeriod: Int
  terrain: [String]
  gravity: Float
  orbitalPeriod: Int
  population: Float
}

type Query {
  films(sortBy: SortFilmsBy = episodeId): [Film!]
  film(id: Int!): Film
  person(id: Int!): Person
  people(sortBy: SortByNameOrId = id): [Person!]
  planets(sortBy: SortByNameOrId = id): [Planet!]
  planet(id: Int!): Planet
}
